package iso4217;

// this file is generated, modifications will be lost

@:expose @:keep
@:enum abstract CurrencyCode(String) to String {
	var AED = 'AED';
	var AFN = 'AFN';
	var ALL = 'ALL';
	var AMD = 'AMD';
	var ANG = 'ANG';
	var AOA = 'AOA';
	var ARS = 'ARS';
	var AUD = 'AUD';
	var AWG = 'AWG';
	var AZN = 'AZN';
	var BAM = 'BAM';
	var BBD = 'BBD';
	var BDT = 'BDT';
	var BGN = 'BGN';
	var BHD = 'BHD';
	var BIF = 'BIF';
	var BMD = 'BMD';
	var BND = 'BND';
	var BOB = 'BOB';
	var BOV = 'BOV';
	var BRL = 'BRL';
	var BSD = 'BSD';
	var BTN = 'BTN';
	var BWP = 'BWP';
	var BYN = 'BYN';
	var BZD = 'BZD';
	var CAD = 'CAD';
	var CDF = 'CDF';
	var CHE = 'CHE';
	var CHF = 'CHF';
	var CHW = 'CHW';
	var CLF = 'CLF';
	var CLP = 'CLP';
	var CNY = 'CNY';
	var COP = 'COP';
	var COU = 'COU';
	var CRC = 'CRC';
	var CUC = 'CUC';
	var CUP = 'CUP';
	var CVE = 'CVE';
	var CZK = 'CZK';
	var DJF = 'DJF';
	var DKK = 'DKK';
	var DOP = 'DOP';
	var DZD = 'DZD';
	var EGP = 'EGP';
	var ERN = 'ERN';
	var ETB = 'ETB';
	var EUR = 'EUR';
	var FJD = 'FJD';
	var FKP = 'FKP';
	var GBP = 'GBP';
	var GEL = 'GEL';
	var GHS = 'GHS';
	var GIP = 'GIP';
	var GMD = 'GMD';
	var GNF = 'GNF';
	var GTQ = 'GTQ';
	var GYD = 'GYD';
	var HKD = 'HKD';
	var HNL = 'HNL';
	var HRK = 'HRK';
	var HTG = 'HTG';
	var HUF = 'HUF';
	var IDR = 'IDR';
	var ILS = 'ILS';
	var INR = 'INR';
	var IQD = 'IQD';
	var IRR = 'IRR';
	var ISK = 'ISK';
	var JMD = 'JMD';
	var JOD = 'JOD';
	var JPY = 'JPY';
	var KES = 'KES';
	var KGS = 'KGS';
	var KHR = 'KHR';
	var KMF = 'KMF';
	var KPW = 'KPW';
	var KRW = 'KRW';
	var KWD = 'KWD';
	var KYD = 'KYD';
	var KZT = 'KZT';
	var LAK = 'LAK';
	var LBP = 'LBP';
	var LKR = 'LKR';
	var LRD = 'LRD';
	var LSL = 'LSL';
	var LYD = 'LYD';
	var MAD = 'MAD';
	var MDL = 'MDL';
	var MGA = 'MGA';
	var MKD = 'MKD';
	var MMK = 'MMK';
	var MNT = 'MNT';
	var MOP = 'MOP';
	var MRO = 'MRO';
	var MUR = 'MUR';
	var MVR = 'MVR';
	var MWK = 'MWK';
	var MXN = 'MXN';
	var MXV = 'MXV';
	var MYR = 'MYR';
	var MZN = 'MZN';
	var NAD = 'NAD';
	var NGN = 'NGN';
	var NIO = 'NIO';
	var NOK = 'NOK';
	var NPR = 'NPR';
	var NZD = 'NZD';
	var OMR = 'OMR';
	var PAB = 'PAB';
	var PEN = 'PEN';
	var PGK = 'PGK';
	var PHP = 'PHP';
	var PKR = 'PKR';
	var PLN = 'PLN';
	var PYG = 'PYG';
	var QAR = 'QAR';
	var RON = 'RON';
	var RSD = 'RSD';
	var RUB = 'RUB';
	var RWF = 'RWF';
	var SAR = 'SAR';
	var SBD = 'SBD';
	var SCR = 'SCR';
	var SDG = 'SDG';
	var SEK = 'SEK';
	var SGD = 'SGD';
	var SHP = 'SHP';
	var SLL = 'SLL';
	var SOS = 'SOS';
	var SRD = 'SRD';
	var SSP = 'SSP';
	var STD = 'STD';
	var SVC = 'SVC';
	var SYP = 'SYP';
	var SZL = 'SZL';
	var THB = 'THB';
	var TJS = 'TJS';
	var TMT = 'TMT';
	var TND = 'TND';
	var TOP = 'TOP';
	var TRY = 'TRY';
	var TTD = 'TTD';
	var TWD = 'TWD';
	var TZS = 'TZS';
	var UAH = 'UAH';
	var UGX = 'UGX';
	var USD = 'USD';
	var USN = 'USN';
	var UYI = 'UYI';
	var UYU = 'UYU';
	var UZS = 'UZS';
	var VEF = 'VEF';
	var VND = 'VND';
	var VUV = 'VUV';
	var WST = 'WST';
	var XAF = 'XAF';
	var XAG = 'XAG';
	var XAU = 'XAU';
	var XBA = 'XBA';
	var XBB = 'XBB';
	var XBC = 'XBC';
	var XBD = 'XBD';
	var XCD = 'XCD';
	var XDR = 'XDR';
	var XOF = 'XOF';
	var XPD = 'XPD';
	var XPF = 'XPF';
	var XPT = 'XPT';
	var XSU = 'XSU';
	var XTS = 'XTS';
	var XUA = 'XUA';
	var XXX = 'XXX';
	var YER = 'YER';
	var ZAR = 'ZAR';
	var ZMW = 'ZMW';
	var ZWL = 'ZWL';

	public static function validate( code: String ) : CurrencyCode
		return switch code.toUpperCase() {
			case "AED": AED;
			case "AFN": AFN;
			case "ALL": ALL;
			case "AMD": AMD;
			case "ANG": ANG;
			case "AOA": AOA;
			case "ARS": ARS;
			case "AUD": AUD;
			case "AWG": AWG;
			case "AZN": AZN;
			case "BAM": BAM;
			case "BBD": BBD;
			case "BDT": BDT;
			case "BGN": BGN;
			case "BHD": BHD;
			case "BIF": BIF;
			case "BMD": BMD;
			case "BND": BND;
			case "BOB": BOB;
			case "BOV": BOV;
			case "BRL": BRL;
			case "BSD": BSD;
			case "BTN": BTN;
			case "BWP": BWP;
			case "BYN": BYN;
			case "BZD": BZD;
			case "CAD": CAD;
			case "CDF": CDF;
			case "CHE": CHE;
			case "CHF": CHF;
			case "CHW": CHW;
			case "CLF": CLF;
			case "CLP": CLP;
			case "CNY": CNY;
			case "COP": COP;
			case "COU": COU;
			case "CRC": CRC;
			case "CUC": CUC;
			case "CUP": CUP;
			case "CVE": CVE;
			case "CZK": CZK;
			case "DJF": DJF;
			case "DKK": DKK;
			case "DOP": DOP;
			case "DZD": DZD;
			case "EGP": EGP;
			case "ERN": ERN;
			case "ETB": ETB;
			case "EUR": EUR;
			case "FJD": FJD;
			case "FKP": FKP;
			case "GBP": GBP;
			case "GEL": GEL;
			case "GHS": GHS;
			case "GIP": GIP;
			case "GMD": GMD;
			case "GNF": GNF;
			case "GTQ": GTQ;
			case "GYD": GYD;
			case "HKD": HKD;
			case "HNL": HNL;
			case "HRK": HRK;
			case "HTG": HTG;
			case "HUF": HUF;
			case "IDR": IDR;
			case "ILS": ILS;
			case "INR": INR;
			case "IQD": IQD;
			case "IRR": IRR;
			case "ISK": ISK;
			case "JMD": JMD;
			case "JOD": JOD;
			case "JPY": JPY;
			case "KES": KES;
			case "KGS": KGS;
			case "KHR": KHR;
			case "KMF": KMF;
			case "KPW": KPW;
			case "KRW": KRW;
			case "KWD": KWD;
			case "KYD": KYD;
			case "KZT": KZT;
			case "LAK": LAK;
			case "LBP": LBP;
			case "LKR": LKR;
			case "LRD": LRD;
			case "LSL": LSL;
			case "LYD": LYD;
			case "MAD": MAD;
			case "MDL": MDL;
			case "MGA": MGA;
			case "MKD": MKD;
			case "MMK": MMK;
			case "MNT": MNT;
			case "MOP": MOP;
			case "MRO": MRO;
			case "MUR": MUR;
			case "MVR": MVR;
			case "MWK": MWK;
			case "MXN": MXN;
			case "MXV": MXV;
			case "MYR": MYR;
			case "MZN": MZN;
			case "NAD": NAD;
			case "NGN": NGN;
			case "NIO": NIO;
			case "NOK": NOK;
			case "NPR": NPR;
			case "NZD": NZD;
			case "OMR": OMR;
			case "PAB": PAB;
			case "PEN": PEN;
			case "PGK": PGK;
			case "PHP": PHP;
			case "PKR": PKR;
			case "PLN": PLN;
			case "PYG": PYG;
			case "QAR": QAR;
			case "RON": RON;
			case "RSD": RSD;
			case "RUB": RUB;
			case "RWF": RWF;
			case "SAR": SAR;
			case "SBD": SBD;
			case "SCR": SCR;
			case "SDG": SDG;
			case "SEK": SEK;
			case "SGD": SGD;
			case "SHP": SHP;
			case "SLL": SLL;
			case "SOS": SOS;
			case "SRD": SRD;
			case "SSP": SSP;
			case "STD": STD;
			case "SVC": SVC;
			case "SYP": SYP;
			case "SZL": SZL;
			case "THB": THB;
			case "TJS": TJS;
			case "TMT": TMT;
			case "TND": TND;
			case "TOP": TOP;
			case "TRY": TRY;
			case "TTD": TTD;
			case "TWD": TWD;
			case "TZS": TZS;
			case "UAH": UAH;
			case "UGX": UGX;
			case "USD": USD;
			case "USN": USN;
			case "UYI": UYI;
			case "UYU": UYU;
			case "UZS": UZS;
			case "VEF": VEF;
			case "VND": VND;
			case "VUV": VUV;
			case "WST": WST;
			case "XAF": XAF;
			case "XAG": XAG;
			case "XAU": XAU;
			case "XBA": XBA;
			case "XBB": XBB;
			case "XBC": XBC;
			case "XBD": XBD;
			case "XCD": XCD;
			case "XDR": XDR;
			case "XOF": XOF;
			case "XPD": XPD;
			case "XPF": XPF;
			case "XPT": XPT;
			case "XSU": XSU;
			case "XTS": XTS;
			case "XUA": XUA;
			case "XXX": XXX;
			case "YER": YER;
			case "ZAR": ZAR;
			case "ZMW": ZMW;
			case "ZWL": ZWL;
			default: throw 'invalid CurrencyCode "$code"';
		}
}
